name: Inception

services:

  mariadb:
    container_name: mariadb
    env_file: .env
    restart: unless-stopped
    build:
      context: ./MariaDB
      dockerfile: Dockerfile
      args:
        - MARIADB_VERSION=$MARIADB_VERSION
    networks:
      - inception
    volumes:
      - mariadb:/usr/share/mariadb
    healthcheck:
      test: [ "CMD-SHELL", "/bin/healthcheck.sh --connect --innodb_initialized" ]
      start_period: 5s
      interval: 30s
      retries: 3

  adminer:
    container_name: adminer
    restart: unless-stopped
    build:
      context: ./Adminer
      dockerfile: Dockerfile
      args:
        - ADMINER_VERSION=$ADMINER_VERSION
    networks:
      - inception
    depends_on:
      - mariadb
    healthcheck:
      test: ["CMD-SHELL", "curl -s http://localhost:8080"]
      start_period: 5s
      interval: 30s
      retries: 3

  nginx:
    container_name: nginx
    restart: unless-stopped
    build:
      context: ./NGinx
      dockerfile: Dockerfile
      args:
        - NGINX_VERSION=$NGINX_VERSION
    networks:
      - inception
    volumes:
      - wordpress-files:/usr/share/nginx
    depends_on:
      - wordpress
    ports :
      - "443:443"
    healthcheck:
      test: ["CMD-SHELL", "curl -sk https://localhost/status"]
      start_period: 5s
      interval: 30s
      retries: 3


  wordpress:
    container_name: wordpress
    env_file: .env
    restart: unless-stopped
    build:
      context: ./WordPress
      dockerfile: Dockerfile
    environment:
      - WP_VERSION=$WP_VERSION
    networks:
      - inception
    volumes:
      - wordpress-files:/usr/share/nginx
    depends_on:
      - mariadb
      - redis
    healthcheck:
      test: ["CMD-SHELL", "ps aux | grep -r \"php-fpm: master process\""]
      start_period: 5s
      interval: 30s
      retries: 3

  redis:
    container_name: redis
    restart: unless-stopped
    build:
      context: ./Redis
      dockerfile: Dockerfile
      args:
        - REDIS_VERSION=$REDIS_VERSION
    networks:
      - inception
    healthcheck:
      test: "[ $(redis-cli ping) = 'PONG' ]"
      start_period: 5s
      interval: 30s
      retries: 3

  portfolio:
    container_name: portfolio
    restart: unless-stopped
    build:
      context: ./Portfolio
      dockerfile: Dockerfile
    networks:
      - inception
    healthcheck:
      test: ['CMD-SHELL', "curl -s http://localhost:5173/portfolio/"]
      start_period: 5s
      interval: 30s
      retries: 3


  vsftpd:
    container_name: vsftpd
    restart: unless-stopped
    build:
      context: ./Vsftpd
      dockerfile: Dockerfile
      args:
        - FTP_USER=$FTP_USER
        - FTP_PASSWORD=$FTP_PASSWORD
    networks:
      - inception
    volumes:
      - wordpress-files:/var/ftp/upload
    healthcheck:
      test: ['CMD-SHELL', "ps aux | grep -r /usr/sbin/vsftpd"]
      start_period: 5s
      interval: 30s
      retries: 3

  net2ftp:
    container_name: net2ftp
    restart: unless-stopped
    build:
      context: ./Net2ftp
      dockerfile: Dockerfile
      args:
        - NET2FTP_VERSION=$NET2FTP_VERSION
    networks:
      - inception
    healthcheck:
      test: ['CMD-SHELL', "wget --spider http://localhost:8081"]
      start_period: 5s
      interval: 30s
      retries: 3

volumes:
  mariadb:
    driver: local
    driver_opts:
      type: none
      o: bind
      device: /home/${USER}/data/mariadb
  wordpress-files:
    driver: local
    driver_opts:
      type: none
      o: bind
      device: /home/${USER}/data/wordpress-files

networks:
  inception:
    driver: bridge
